/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Graphics;
import modele.home.Acces;
import modele.home.Lieu;
import modele.home.Piece;

/**
 *
 * @author anisbenyoub
 */
public class MapLieu extends javax.swing.JPanel {

    public Lieu monLieu;
    /**
     * Creates new form MapLieu
     */
    public MapLieu(Lieu unLieu) {
        
        initComponents();
        monLieu=unLieu;
        this.setVisible(true);
        
    }

    public void drawMap(Graphics g)
    {
        g.setColor(Color.blue);


        for(Piece p:monLieu.getMesPieces())
        {
            g.drawRect(p.getX(), p.getY(), p.getX()+p.largeurX, p.getY()+p.largeurY);
        }
        g.setColor(Color.red);
        for(Acces a:monLieu.getMesAcces())
        {
            g.drawRect(a.getX(), a.getY(), a.getX()+a.taillex, a.getY()+a.tailley);
        }
    }	
    @Override
     public void paintComponent(Graphics g) {
		super.paintComponent(g);
		drawMap(g);

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas3 = new java.awt.Canvas();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas3;
    // End of variables declaration//GEN-END:variables
}
